CREATE DATABASE IF NOT EXISTS java_odyssey
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE java_odyssey;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS player_progress (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    level INT NOT NULL DEFAULT 1,
    coins INT NOT NULL DEFAULT 0,
    hp INT NOT NULL DEFAULT 100,
    xp INT NOT NULL DEFAULT 0,
    total_xp INT NOT NULL DEFAULT 0,
    phase VARCHAR(50) NOT NULL DEFAULT 'menu',
    current_scene VARCHAR(100) DEFAULT NULL,
    current_position VARCHAR(50) DEFAULT NULL,
    savepoint_scene VARCHAR(100) DEFAULT NULL,
    savepoint_label VARCHAR(150) DEFAULT NULL,
    save_state LONGTEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_player_progress_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leaderboard_entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL,
    level INT NOT NULL DEFAULT 1,
    xp INT NOT NULL DEFAULT 0,
    time_completed INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_leaderboard_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
